programme: main.o mouvment.o evan.o animation.o
	gcc main.o mouvment.o evan.o animation.o -o programme -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
main.o:main.c
	gcc -c main.c -g 
evan.o:evan.c
	gcc -c evan.c -g
mouvment.o:mouvment.c
	gcc -c mouvment.c -g
animation.o:animation.c
	gcc -c animation.c -g
